// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7ckwHah1dwzrXN8OI_iBJguJJWcn-48',
    appId: '1:1044418593849:web:36fc1782c2d6f9c541f9e8',
    messagingSenderId: '1044418593849',
    projectId: 'test-8a5ad',
    authDomain: 'test-8a5ad.firebaseapp.com',
    storageBucket: 'test-8a5ad.firebasestorage.app',
    measurementId: 'G-3K74KXHXRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSv-OuCUwZMEYmiQG9jHcGMN4Tj-mTKKA',
    appId: '1:1044418593849:android:a57e7fd4bd25aa3741f9e8',
    messagingSenderId: '1044418593849',
    projectId: 'test-8a5ad',
    storageBucket: 'test-8a5ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_UFrmyqQ10qN3rf28H-hILQxwvJlqbY',
    appId: '1:1044418593849:ios:473cb6ba59c0384f41f9e8',
    messagingSenderId: '1044418593849',
    projectId: 'test-8a5ad',
    storageBucket: 'test-8a5ad.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ_UFrmyqQ10qN3rf28H-hILQxwvJlqbY',
    appId: '1:1044418593849:ios:473cb6ba59c0384f41f9e8',
    messagingSenderId: '1044418593849',
    projectId: 'test-8a5ad',
    storageBucket: 'test-8a5ad.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL7ckwHah1dwzrXN8OI_iBJguJJWcn-48',
    appId: '1:1044418593849:web:04568ffb16b45c3e41f9e8',
    messagingSenderId: '1044418593849',
    projectId: 'test-8a5ad',
    authDomain: 'test-8a5ad.firebaseapp.com',
    storageBucket: 'test-8a5ad.firebasestorage.app',
    measurementId: 'G-GT7C987WG7',
  );

}